/**
 * Stateで使う定数
 */
export const ANSWER_NOT_POSTED = 'ANSWER_NOT_POSTED';
export const ANSWER_POSTED_FAILED = 'ANSWER_POSTED_FAILED';
export const ANSWER_POSTED_SUCCESS = 'ANSWER_POSTED_SUCCESS';
export const ANSWER_POSTING = 'ANSWER_POSTING';
export const SURVEY_NOT_POSTED = 'SURVEY_NOT_POSTED';
export const SURVEY_POSTED_FAILED = 'SURVEY_POSTED_FAILED';
export const SURVEY_POSTED_SUCCESS = 'SURVEY_POSTED_SUCCESS';
export const SURVEY_POSTING = 'SURVEY_POSTING';
